# Generated by Django 5.2.1 on 2025-05-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='tipo',
            field=models.CharField(choices=[('PROFESSOR', 'Professor'), ('GESTOR', 'Gestor'), ('OUTRO', 'Outro')], default='PROFESSOR', max_length=10),
        ),
    ]
