# Generated by Django 5.2.2 on 2025-06-05 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professorgestor',
            old_name='Usuario',
            new_name='Tipo_usuario',
        ),
    ]
