# Generated by Django 5.2.2 on 2025-06-05 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_usuario_professorgestor_tipo_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professorgestor',
            old_name='Tipo_usuario',
            new_name='Professor_responsavel',
        ),
    ]
