# Generated by Django 5.2.2 on 2025-06-05 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_tipo_usuario_professorgestor_professor_responsavel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professorgestor',
            old_name='Professor_responsavel',
            new_name='Usuario',
        ),
    ]
